function [ok, status, time] = solveMultiPhase(simcase, varargin)
    opt = struct('resetData', false, ...
        'injectionTimeStep' , 10*minute, ...
        'settleTimeStep'    , 10*minute,...
        'dim'               , 3, ...
        'usedeck'           , true, ...
        'Jutul'             , false, ...
        'direct_solver'     , false);

    [opt, extra] = merge_options(opt, varargin{:});
    dirName       = fullfile(simcase.dataOutputDir, simcase.casename);

    [state0, model, schedule, nls] = setup11A(simcase, 'direct_solver', opt.direct_solver, extra{:});
    assert(all(state0.s(:,2)==0))
    assert(all(state0.s(:,1)==1))

    problem = packSimulationProblem(state0, model, ...
        schedule, simcase.casename, ...
                    'Directory', dirName, ... %getdirname(dirname)
                    'NonLinearSolver', nls, ...
                    'Name'           , 'multiphase');
    
    restartStep = nan;
    checkTooMany = true;
    if opt.resetData
        restartStep = 1;
        checkTooMany = false;
    end
    tic();
    if opt.Jutul
        projPath = 'C:\Users\holme\OneDrive\Dokumenter\_Studier\Prosjekt\11SPE\src';
        outputfolder = 'C:\Users\holme\OneDrive\Dokumenter\_Studier\Prosjekt\11SPE\src\output';
        [ws, states] = simulatePackedProblemJutul(problem, 'name', simcase.casename, 'project', projPath, 'path', outputfolder);
        ok = true;%?
    else
    [ok, status] = simulatePackedProblem(problem, ...
                                  'restartStep', restartStep, ...
                                  'continueOnError', false, ...
                                  'checkTooMany', checkTooMany, ...
                                  'continueOnError', true);
    end
    time = toc();
end
